env:
  browser: false
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  no-tabs:
    - error
    - allowIndentationTabs: true
  no-console: off
  consistent-return: 0
  no-unused-vars: 0
  class-methods-use-this: 0
  implicit-arrow-linebreak: 0
  no-await-in-loop: 0