version: "3.9"
services:
  server:
    container_name: social-network-server-prod
    build: .
    restart: on-failure
    depends_on:
      - mongo
    networks:
      - social-network
  mongo:
    image: mongo:latest
    container_name: social-network-mongo-prod
    networks:
      - social-network
    volumes:
      - social-network-mongo:/etc/mongo
  
  nginx:
    image: nginx:latest
    container_name: social-network-nginx-prod
    depends_on:
      - server
      - mongo
    networks:
      - social-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:8080
    
networks:
  social-network:
    driver: bridge

volumes:
  social-network-mongo: